# -*- coding: utf-8 -*-
"""RoBERTa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tvYh32u7yfhOUk2P-aFQDnHqEHbhEr0h
"""

import pandas as pd
import re # library called regular expresions that helps to search, match, and manipulate strings using patterns.
import nltk # library called natural language toolkit that allows us to tokenize, classify and clean language data.
from nltk.corpus import stopwords # for preprocessing
from nltk.stem import WordNetLemmatizer # for preprocessing
from transformers import RobertaTokenizer, RobertaForSequenceClassification, Trainer, TrainingArguments, TrainerCallback
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
import torch
from torch.utils.data import Dataset # allows to create a class object dataset
import matplotlib.pyplot as plt
import seaborn as sns

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

# Load the dataset
url = 'https://raw.githubusercontent.com/pinchunc/NMA_DL_SentimentAnalysis/main/data/hippoCorpusV2.csv'
df = pd.read_csv(url)
df = df[['story', 'memType', 'stressful']].dropna() # we exclude n/a spaces
df.head()

# @title Exploratory Data Analysis

# Count number of words in each story
df['word_count'] = df['story'].astype(str).apply(lambda x: len(x.split()))
word_count_average = df['word_count'].mean()

# Plot distribution of word count
df['word_count'].hist(bins=50)
plt.xlabel("Number of words")
plt.ylabel("Number of stories")
plt.title("Story length distribution")
plt.show()

# Plot distribution of stress levels
plt.figure(figsize=(6, 4))
sns.histplot(df['stressful'], discrete=True, kde=False)
plt.title('Histogram of Stress Levels')
plt.xlabel('Stress Level')
plt.ylabel('Count')
plt.show()

# Plot distribution of memory types
plt.figure(figsize=(6, 4))
sns.histplot(df['memType'], discrete=True, kde=False)
plt.title('Histogram of Memory Types')
plt.xlabel('Memory Type')
plt.ylabel('Count')
plt.show()

print(f"Word Count Average = {word_count_average}")
print(df['stressful'].value_counts().sort_index())
print(df['memType'].value_counts())

# @title Relabel Stress Levels
def relabel_stress(level):
  if level == 1:
    return 0
  elif level in [2, 3]:
    return 1
  else:
    return 2

df['stress_label'] = df['stressful'].apply(relabel_stress)

# Plot new grouped stress levels
plt.figure(figsize=(6, 4))
sns.histplot(df['stress_label'], discrete=True, kde=False)
plt.title('Histogram of Grouped Stress Levels')
plt.xlabel('Stress Category')
plt.ylabel('Count')
plt.xticks([0, 1, 2], ['Low', 'Normal', 'High'])
plt.show()

# @title 1) Preprocessing
# Minimal cleaning because we are using RoBERTa that is trained already in raw unnormalised data
def minimal_clean(text):
    text = str(text)                              # 1) Ensure it's a string
    text = re.sub(r'\s+', ' ', text)              # 2) Replace multiple spaces/newlines with a single space
    text = text.strip()                           # 3) Trim leading/trailing whitespace
    return text

df["clean_story"] = df["story"].apply(minimal_clean)

# Minimal preprocessing for RoBERTa using pandas (faster)
# df['story'] = df['story'].astype(str).fillna('').str.strip()

# Encode labels as intergers for classification
df['stress_label'] = df['stress_label'].astype(int)

# @title 2) Tokenization with RoBERTa tokenizer
tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

# Tokenize only first "max_length" words of each story (truncate if they exceed the word limit and pad to mantain length of stories consistent)
tokens = tokenizer(list(df['clean_story']), truncation=True, padding='max_length', max_length=400)

# @title 3) Create Class Object
# Create an object of class StressDataset to use Hugging Face's 'Trainer'
class StressDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=200):
      """
        texts: list or array of input texts (cleaned stories)
        labels: list or array of corresponding stress level labels
        tokenizer: Hugging Face Roberta Tokenizer
        max_len: max length of tokenized input (default = 400 tokens)
      """

      self.texts = texts
      self.labels = labels
      self.tokenizer = tokenizer
      self.max_len = max_len

    def __getitem__(self, idx):
        encoding = self.tokenizer(    # tokenize the text
            self.texts[idx],          # retrieves the story text at index 'idx'
            truncation=True,          # cuts the input off it it exceeds max_len
            padding='max_length',     # pads the input up to max_len tokens
            max_length=self.max_len,  # sets the maximum length of tokens
            return_tensors='pt'       # Returns tensors in PyTorch format
        )

        # This diccionary with token IDs, masks for padding and labels of stress levels
        return {
            'input_ids': encoding['input_ids'].squeeze(),               # token IDs of the story text
            'attention_mask': encoding['attention_mask'].squeeze(),     # binary mask (1s and 0s) telling the model which tokens are content and which are padding.
            'labels': torch.tensor(self.labels[idx], dtype=torch.long)  # retrieves the corresponding label of the story at index 'idx' and converts it into a PyTorch tensor with interger type (long) for classification
        }

    def __len__(self):
        return len(self.texts) # this returns the number of stories in the dataset

# @title 4) Split the dataset (training, validation and testing)
# Step 1: Split into 80% train and 20% temp (for val + test)
train_texts, temp_texts, train_labels, temp_labels = train_test_split(
    df["clean_story"].tolist(),
    df["stress_label"].tolist(),
    test_size=0.2,
    random_state=42
)

# Step 2: Split temp into 50% val and 50% test → 10% each of the full dataset
val_texts, test_texts, val_labels, test_labels = train_test_split(
    temp_texts,
    temp_labels,
    test_size=0.5,
    random_state=42
)

# Build datasets
train_dataset = StressDataset(train_texts, train_labels, tokenizer)
val_dataset = StressDataset(val_texts, val_labels, tokenizer)
test_dataset = StressDataset(test_texts, test_labels, tokenizer)

# @title 5) Define Model: RoBERTa
# RoBERTa Model with 3 labels for classification
model = RobertaForSequenceClassification.from_pretrained(
    'roberta-base',
    num_labels=3,
)

# @title 6) Define Evaluation Metrics
# Evaluation metrics
def compute_metrics(pred):
    labels = pred.label_ids               # true labels
    preds = pred.predictions.argmax(-1)   # from the predictions (logits), it picks the index of the class with the highest predicted score.

    # Returns a diccionary so the 'Trainer' can log them
    return {
        'accuracy': accuracy_score(labels, preds),                    # Fraction of predictions that were exactly correct
        'f1_macro': f1_score(labels, preds, average='macro'),         # F1-score (combination of Precision and Recall) avg equally across all classes (not weighted by class frequency - good for imbalanced data)
        'precision': precision_score(labels, preds, average='macro'), # Precision avg across all classes
        'recall': recall_score(labels, preds, average='macro')        # Recall avg across all classes
    }

# @title 7) Define Training Arguments
# Training arguments
training_args = TrainingArguments(
    output_dir='./results',         # Directory where model checkpoints and other outputs will be saved during training
    learning_rate=2e-4,             # Common starting LR for transformers
    per_device_train_batch_size=16, # Reasonable for most GPUs
    per_device_eval_batch_size=32,  # Larger batch for evaluation
    num_train_epochs=3,             # Commonly between 3 and 5
    weight_decay=0.01,              # L2 regularization: prevents overfitting by discouraging large weights

    # Training loss
    logging_strategy="steps",
    logging_steps=100,              # Log training loss and metrics every 100 steps

    # Evaluation metrics
    eval_strategy="steps",
    eval_steps = 100,               # Evaluate every 100 steps

    # Save model
    save_strategy="steps",
    save_steps=100,
    save_total_limit=1,             # Keeps only 1 checkpoint in the output_dir, deleting older ones to control disk usage

    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    greater_is_better=True,

    logging_dir='./logs',           # Directory where log files will be written
    report_to='none',               # disable wanb
)

# @title 8) Define Trainer
# Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

# @title 9) Train, Validate and Evaluate Model
# Train model
trainer.train()

# Evaluate
test_results = trainer.evaluate(test_dataset)
print("Final Test Set Results:", test_results)

# @title Plot Training Loss and Validation Loss and Accuracy
# Convert logs to DataFrame
log_history = pd.DataFrame(trainer.state.log_history)

# Plot training loss
plt.figure(figsize=(10, 5))
train_logs = log_history.dropna(subset=["loss"])
plt.plot(train_logs["step"], train_logs["loss"], label="Training Loss")
plt.xlabel("Step")
plt.ylabel("Loss")
plt.title("Training Loss Over Time")
plt.legend()
plt.grid()
plt.show()

# Plot validation loss and accuracy
eval_logs = log_history.dropna(subset=["eval_loss"])

plt.figure(figsize=(10, 5))
plt.plot(eval_logs["step"], eval_logs["eval_loss"], label="Validation Loss")
if "eval_accuracy" in eval_logs.columns:
    plt.plot(eval_logs["step"], eval_logs["eval_accuracy"], label="Validation Accuracy")
plt.xlabel("Step")
plt.ylabel("Value")
plt.title("Validation Loss and Accuracy")
plt.legend()
plt.grid()
plt.show()